### ISSUE TITLE
Using Nisaba via Pynini: cannot find rules_python

### ISSUE THREAD

**Issue by ryskina** [google-research/nisaba#31]
Hello,

I followed the installation instructions in the README to install and build Nisaba on my personal MacOS machine. Bazel is working and the small unit tests are passing. 

However, when I try to use Nisaba FSTs in Pynini following the examples [here](https://github.com/google-research/nisaba/blob/main/nisaba/brahmic/README.md), imports from `rules_python` fail.  I am getting the same error with both the Anaconda Python 3.7 and the system Python 2.7.  

Is there some further disconnect between my Python and Bazel, or am I maybe missing a step here? Thanks!

**Comment by agutkin** [comment]
I presume you are not using Bazel to build your code?

**Comment by agutkin** [comment]
In case the answer to the above question is `yes` then I presume you can try to simply copy[run_files.py](https://github.com/bazelbuild/rules_python/blob/master/python/runfiles/runfiles.py) into your code and use as is. It is a helper library that has no Bazel internal dependencies.

**Comment by agutkin** [comment]
... and the easiest option - simply ignore the `run_files` Bazel API (if you are not using Bazel). After all, all you need is a FAR file which can be simply copied from the `bazel-bin` directory where it is generated. The reason the `run_files` API is there is to facilitate running as part of the Bazel ecosystem, which I suppose is unnecessary if you are not using it.

**Comment by ryskina** [comment]
Thank you for the reply! You're right, I was not building my code with Bazel. 

Removing `run_files` and manually appending the path to `bazel-bin` to the FAR filename worked, thank you!
