### ISSUE TITLE
Telugu visual rewrite missing rule

### ISSUE THREAD

**Issue by ramSeraph** [google-research/nisaba#500]
I think there is a visual rewrite rule which was missed for Telugu.

It is mentioned in section 12.7( under Special Characters ) of the [unicode 12 document](https://www.unicode.org/versions/Unicode12.1.0/ch12.pdf)

```
U+0C56 TELUGU AI LENGTH MARK is provided as an encoding for the second element of the surroundrant vowel
U+0C48 TELUGU VOWEL SIGN AI. 
```

The rule would be:
```
item {
  uname: ["SIGN E", "AI LENGTH MARK"] raw: "ై"
  to_uname: "SIGN AI" to_raw: "ై"
}

**Comment by agutkin** [comment]
Thank you. You are right, it seems to be a genuine omission.

**Comment by agutkin** [comment]
The relevant rewrite happens earlier in the cascade during the NFC normalization.

**Comment by ramSeraph** [comment]
I see.. sorry for the false alarm.
